package cps

// Content of that file was generated using dxe-tools. Please refer to dxe-tools README for more information.

var warningMap = map[string]string{
	"CERTIFICATE_ADDED_TO_TRUST_CHAIN":                                 `A certificate was added to the new trust chain.`,
	"CERTIFICATE_ALREADY_LOADED":                                       `There is a problem deploying the certificate.  Please contact your Akamai support team to resolve the issue.`,
	"CERTIFICATE_DATA_BLANK_OR_MISSING":                                `Certificate data is blank or missing.`,
	"CERTIFICATE_DATA_EXCEEDS_MAXIMUM":                                 `Number of entries in certificate exceeds the maximum allowed.`,
	"CERTIFICATE_EXPIRATION_DATE_BEYOND_MAX_DAYS":                      `The certificate has a validity period of greater than 397 days. This certificate will not be accepted by all major browsers for SSL/TLS connections. Please work with your Certificate Authority to reissue the certificate with an acceptable lifetime.`,
	"CERTIFICATE_EXPIRATION_DATE_BEYOND_RANGE":                         `This certificate is set to expire in more than 3 years. Akamai recommends validity of 3 years or less.`,
	"CERTIFICATE_EXPIRATION_DATE_IN_NEAR_FUTURE":                       `This certificate will expire in the near future.`,
	"CERTIFICATE_EXPIRATION_DATE_TOO_LATE":                             `This certificate expiration date is longer than expected.`,
	"CERTIFICATE_EXPIRATION_TOO_SHORT":                                 `This certificate has a short lifetime and will expire soon.`,
	"CERTIFICATE_EXPIRED":                                              `This certificate has already expired.`,
	"CERTIFICATE_HAS_NULL_ISSUER":                                      `Certificate has a null issuer`,
	"CERTIFICATE_HAS_NULL_SERIAL_NUMBER":                               `Certificate has a null serial number`,
	"CERTIFICATE_KMI_DATA_EXPIRED":                                     `The KMI entry for the new certificate expired.`,
	"CERTIFICATE_KMI_DATA_EXPIRES_SOON":                                `The KMI entry for the new certificat will expire soon.`,
	"CERTIFICATE_KMI_DATA_EXPIRES_TODAY":                               `The KMI entry for the new certificate will expire today.`,
	"CERTIFICATE_KMI_DATA_INCOMPLETE":                                  `The KMI data is not complete for the new certificate.`,
	"CERTIFICATE_KMI_DATA_MISSING":                                     `No KMI data is available for the new certificate.`,
	"CERTIFICATE_KMI_DATA_SCHEDULED_FOR_DELETION":                      `The KMI entry was scheduled for deletion.`,
	"CERTIFICATE_KMI_DATA_WILL_BE_DELETED_SOON":                        `The KMI entry for the new certificat will be deleted soon.`,
	"CERTIFICATE_KMI_DATA_WILL_BE_DELETED_TODAY":                       `The KMI entry for the new certificate will be deleted today.`,
	"CERTIFICATE_MISSING_CN_FROM_SAN_LIST":                             `The Common Name (CN) is missing from the SAN list.`,
	"CERTIFICATE_MISSING_IN_TRUST_CHAIN":                               `A certificate is missing from the new trust chain`,
	"CERTIFICATE_NOT_ACTIVE_IN_KMI":                                    `The new certificate is not active in KMI.`,
	"CERTIFICATE_NOT_PEM_FORMAT":                                       `This certificate format is not supported. The supported format for certificates and trust chains is PEM (base64).`,
	"CERTIFICATE_NOT_YET_VALID":                                        `The certificate is not yet valid.`,
	"CERTIFICATE_NULL_OR_EMPTY":                                        `Null or empty certificate.`,
	"CERTIFICATE_PARSING_ERROR":                                        `Error parsing certificate.`,
	"CERTIFICATE_SELF_SIGNED":                                          `The Issuer and Subject of the end-entity certificate are identical. This is not allowed.`,
	"CERTIFICATE_SERIAL_NUMBER_ON_ANDROID_BLACK_LIST":                  `This certificate may get \"Invalid CA\" errors on some Android devices, due to serial number issues.`,
	"CERTIFICATE_SIGNATURE_MISMATCH":                                   `Certificate signed with add different signature algorithm than requested.`,
	"CERTIFICATE_TRUST_CHAIN_MISSING":                                  `Certificate and/or Trust Chain data is missing.`,
	"CERTIFICATE_VS_NETWORK_SAN_REMOVED_FROM_CERT_LIVE_ON_NETWORK":     `A SAN name that was removed from certificate is still live on the network.`,
	"CROSS_SIGNED_ROOT_IN_TRUST_CHAIN":                                 `Crossed signed roots were found in the trust chain.`,
	"CSR_EXPIRED":                                                      `The key for this certificate has expired. You need to create and submit a new certificate.`,
	"CSR_PARSING_ERROR":                                                `Error parsing CSR.`,
	"CSR_VS_CERTIFICATE_ADDITIONAL_SAN_IN_SAN_LIST_IN_CERTIFICATE":     `A SAN name was added to the certificate.`,
	"CSR_VS_CERTIFICATE_BOTH_SUBJECT_FIELDS_ARE_NULL_OR_EMPTY":         `Both expected and found values are empty. They cannot be null or empty at the same time.`,
	"CSR_VS_CERTIFICATE_CN_CASE_MISMATCH":                              `The case of the Common Name (CN) on the certificate does not match the CN on the CSR.`,
	"CSR_VS_CERTIFICATE_CN_MISMATCH":                                   `The Common Name (CN) on this certificate does not match the CSR.`,
	"CSR_VS_CERTIFICATE_CN_MISSING":                                    `The Common Names (CN) for both certificate and CSR must be non-null and non-empty.`,
	"CSR_VS_CERTIFICATE_C_FIELD_ADDITIONAL_IN_CERTIFICATE":             `The value for C is missing in the CSR, but is present in the certificate`,
	"CSR_VS_CERTIFICATE_C_FIELD_MISMATCH":                              `Value for C differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_C_FIELD_MISSING_IN_CERTIFICATE":                `The value for C is present in the CSR, but missing in the certificate.`,
	"CSR_VS_CERTIFICATE_KEY_MISMATCH":                                  `This certificate was not generated from the CSR that Akamai generated.`,
	"CSR_VS_CERTIFICATE_L_FIELD_ADDITIONAL_IN_CERTIFICATE":             `The value for L is missing in the CSR, but is present in the certificate.`,
	"CSR_VS_CERTIFICATE_L_FIELD_MISMATCH":                              `Value for L differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_L_FIELD_MISSING_IN_CERTIFICATE":                `Value for L is missing in the certificate.`,
	"CSR_VS_CERTIFICATE_MISSING_SAN_FROM_SAN_LIST_IN_CERTIFICATE":      `A SAN name is missing from the certificate.`,
	"CSR_VS_CERTIFICATE_OU_FIELD_ADDITIONAL_IN_CERTIFICATE":            `The value for OU is missing in the CSR, but is present in the certificate.`,
	"CSR_VS_CERTIFICATE_OU_FIELD_MISMATCH":                             `The value for OU differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_OU_FIELD_MISSING_IN_CERTIFICATE":               `The value for OU is missing from the certificate.`,
	"CSR_VS_CERTIFICATE_O_FIELD_ADDITIONAL_IN_CERTIFICATE":             `The value for O is missing from the CSR, but is present in the certificate.`,
	"CSR_VS_CERTIFICATE_O_FIELD_MISMATCH":                              `The value for O differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_O_FIELD_MISSING_IN_CERTIFICATE":                `The value for O is missing in the certificate.`,
	"CSR_VS_CERTIFICATE_SAN_CASE_MISMATCH":                             `A SAN name differs in case on the certificate.`,
	"CSR_VS_CERTIFICATE_ST_FIELD_ADDITIONAL_IN_CERTIFICATE":            `The value for ST is missing in the CSR but is present in the certificate.`,
	"CSR_VS_CERTIFICATE_ST_FIELD_MISMATCH":                             `Value for ST differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_ST_FIELD_MISSING_IN_CERTIFICATE":               `The value for ST is missing in the certificate.`,
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_CASE_MISMATCH":                   `A subject field differs in case between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH":                        `A subject field differs between the CSR and the certificate.`,
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH_MISSING_IN_CERTIFICATE": `A subject field is missing from the certificate.`,
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH_MISSING_IN_CSR":         `A subject field is missing in the CSR, but is present in the certificate.`,
	"DNS_NAME_ISSUER_FORBIDDEN_CAA_RECORD":                             `DNS name forbids CA issuer in CAA record.`,
	"DNS_NAME_ISSUER_NOT_IN_CAA_RECORD":                                `DNS name <dnsName> allows CA issuers <caaIssuers>. Configured issuers are <issuers>`,
	"DNS_NAME_IS_NO_LONGER_CONTAINED":                                  `A DNS name is no longer contained; it will be dropped.`,
	"DNS_NAME_LONGER_THEN_255_CHARS":                                   `DNS name is longer than 255 characters.`,
	"DNS_NAME_NOT_CNAMED":                                              `DNS name not CNAMEd for auto validation.`,
	"DNS_NAME_NOT_CONTAINED":                                           `DNS name <dnsName> is not contained.`,
	"DNS_NAME_NULL_OR_EMPTY":                                           `DNS name is either null or empty.`,
	"DNS_QUERY_NAME_SERVER_TIMEOUT":                                    `DNS name server query timeout`,
	"DNS_TEXT_PARSE":                                                   `DNS Text Parse Exception`,
	"DNS_UNKNOWN_HOST":                                                 `DNS Unknown Host Exception`,
	"DOMAIN_NAME_INVALID":                                              `Domain name is invalid.`,
	"END_ENTITY_CERT_IN_TRUST_CHAIN":                                   `The end-entity certificate appears in the trust chain. This is not allowed. It is being automatically removed from the trust chain.`,
	"EXTRA_CERT_IN_TRUST_CHAIN":                                        `Extra certificates were found in the chain and are being removed.`,
	"FIXED_TRUST_CHAIN_PARSING_ERROR":                                  `Error parsing expected trust chains.`,
	"INVALID_CERTIFICATE":                                              `There is a problem processing the certificate.  Please contact your Akamai support team to resolve the issue.`,
	"INVALID_CSR":                                                      `There is a problem processing the CSR.  Please contact your Akamai support team to resolve the issue.`,
	"MULTIPLE_TRUST_CHAINS":                                            `There are multiple trust chains.`,
	"NAMED_TRUST_CHAIN_MISMATCH":                                       `Trust-chain does not match the trust-chain that was requested.`,
	"NAME_CONSTRAINTS_CN_MISSING":                                      `Name constraints not validated for certificates without a CN.`,
	"NAME_CONSTRAINTS_VIOLATION":                                       `The certificate chain violates at least one name constraint.`,
	"OVERLAPPING_TRAFFIC_CLASS":                                        `Some of the domains being provisioned exist on another certificate. Akamai recommends against overlapping names on Enhanced TLS and Standard TLS certificates except during digital property migrations. Enhanced TLS traffic could be misdirected in the event of DNS misconfiguration and treated as Standard TLS until the overlap is eliminated.`,
	"RETRY_REQUIRED":                                                   `Action Retry Required`,
	"SET_STRICT_CHECK_FALSE":                                           `Set strict CERT check FALSE.`,
	"SNI_DNS_OVERLAP":                                                  `A DNS Name is overlapping a DNS name of one or more enrollments.`,
	"THIRD_PARTY_BLACKLISTED_TRUST_CHAIN_INTERMEDIATE_CERTIFICATE":     `A third party trust chain intermediate certificate is blacklisted.`,
	"THIRD_PARTY_BLACKLISTED_TRUST_CHAIN_ROOT_CERTIFICATE":             `A third party trust chain root certificate is blacklisted.`,
	"TRUST_CHAIN_DOES_NOT_INCLUDE_TRUSTED_CERTIFICATE":                 `The trust chain for this certificate does not match the expected trust chain for this type of certificate.`,
	"TRUST_CHAIN_EMPTY_AND_CERTIFICATE_SIGNED_BY_NON_STANDARD_ROOT":    `The trust chain is empty and the end-entity certificate may have been signed by a non-standard root certificate.`,
	"TRUST_CHAIN_EXPIRED":                                              `A certificate in the trust chain is expired.`,
	"TRUST_CHAIN_EXPIRED_BEFORE_EE":                                    `A certificate in the trust chain expires before the end-entity.`,
	"TRUST_CHAIN_HAS_NULL_ISSUER":                                      `A trust chain certificate has a null issuer.`,
	"TRUST_CHAIN_HAS_NULL_SERIAL_NUMBER":                               `A trust chain certificate has a null serial number`,
	"TRUST_CHAIN_INCLUDES_STANDARD_ROOT_CERTIFICATE":                   `The trust chain includes a standard root certificate. This is not a typical practice.`,
	"TRUST_CHAIN_INVALID":                                              `This certificate trust chain is invalid because no trust chain was found.`,
	"TRUST_CHAIN_NOT_PEM_FORMAT":                                       `This trust chain format is not supported. The supported format for certificates and trust chains is PEM (base64).`,
	"TRUST_CHAIN_NOT_YET_VALID":                                        `A trust chain certificate is not yet valid.`,
	"TRUST_CHAIN_NULL_OR_EMPTY":                                        `Trust chain is empty.`,
	"TRUST_CHAIN_NULL_OR_EMPTY_DETAILED":                               `The certificate trust chain is invalid or empty.`,
	"TRUST_CHAIN_PARSING_ERROR":                                        `Failed to parse trust chain.`,
	"TRUST_CHAIN_PARSING_ERROR_DETAILED":                               `Unable to parse certificate trust chain.`,
	"TRUST_CHAIN_PREVIOIS_NULL_OR_EMPTY":                               `Previous Certificate trust chain is null or empty.`,
	"TRUST_CHAIN_TERMINATES_WITH_NON_STANDARD_CERTIFICATE":             `The trust chain terminates with a non-standard root certificate.`,
	"TRUST_CHAIN_VERIFY_FAILED":                                        `One of the trust chain certificates or the end-entity failed to verify.`,
	"UNEXPECTED_TRUST_CHAIN":                                           `Unexpected trust chain for this certificate.`,
	"UNSORTED_TRUST_CHAIN":                                             `The trust chain was unsorted, so it has been cleaned up.`,
	"VALIDATION_EXCEPTION":                                             `Validation error.`,
	"X509_CERTIFICATE_INVALID_SIGNATURE":                               `Really shouldn't happen, x509Certificates with invalid signatures`,
}
