package cps

// Content of that file was generated using dxe-tools. Please refer to dxe-tools README for more information.

var warningMap = map[string]string{
	"CERTIFICATE_ADDED_TO_TRUST_CHAIN":                                 "Certificate Added to the new Trust Chain: <issuerX500Principal>",
	"CERTIFICATE_ALREADY_LOADED":                                       "There is a problem deploying the '<keyAlgorithm>' certificate.  Please contact your Akamai support team to resolve the issue.",
	"CERTIFICATE_DATA_BLANK_OR_MISSING":                                "Certificate data is blank or missing.",
	"CERTIFICATE_DATA_EXCEEDS_MAXIMUM":                                 "<dataType> contains <size> entries and that exceeds the maximum of <maximum>.",
	"CERTIFICATE_EXPIRATION_DATE_BEYOND_MAX_DAYS":                      "The '<keyAlgorithm>' certificate is set to expire in [<certificateExpirationYears>] years, [<certificateExpirationMonths>] months. The certificate has a validity period of greater than 397 days. This certificate will not be accepted by all major browsers for SSL/TLS connections. Please work with your Certificate Authority to reissue the certificate with an acceptable lifetime.",
	"CERTIFICATE_EXPIRATION_DATE_BEYOND_RANGE":                         "This certificate is set to expire in [<certificateExpirationYears>] years, [<certificateExpirationMonths>] months. Akamai recommends validity of 3 years or less.",
	"CERTIFICATE_EXPIRATION_DATE_IN_NEAR_FUTURE":                       "The '<keyAlgorithm>' certificate will expire in the near future.",
	"CERTIFICATE_EXPIRATION_DATE_TOO_LATE":                             "This certificate is set to expire in [<certificateExpirationYears>] years, [<certificateExpirationMonths>] months. Akamai recommends validity of [<maxCertificateExpirationYears>] years or less.",
	"CERTIFICATE_EXPIRATION_TOO_SHORT":                                 "The '<keyAlgorithm>' certificate has a short lifetime and will expire within the next <certificateExpirationDays> days.",
	"CERTIFICATE_EXPIRED":                                              "This certificate has already expired.",
	"CERTIFICATE_HAS_NULL_ISSUER":                                      "Certificate has a null issuer",
	"CERTIFICATE_HAS_NULL_SERIAL_NUMBER":                               "Certificate has a null serial number",
	"CERTIFICATE_KMI_DATA_EXPIRED":                                     "The KMI entry for the new certificate expired <expiredDays> day(s) ago.",
	"CERTIFICATE_KMI_DATA_EXPIRES_SOON":                                "The KMI entry for the new certificat will expire in <expiresInDays> day(s).",
	"CERTIFICATE_KMI_DATA_EXPIRES_TODAY":                               "The KMI entry for the new certificate will expire today.",
	"CERTIFICATE_KMI_DATA_INCOMPLETE":                                  "The KMI data is not complete for the new certificate.",
	"CERTIFICATE_KMI_DATA_MISSING":                                     "No KMI data is available for the new certificate.",
	"CERTIFICATE_KMI_DATA_SCHEDULED_FOR_DELETION":                      "The KMI entry was scheduled for deletion <deletedInDays> day(s) ago.",
	"CERTIFICATE_KMI_DATA_WILL_BE_DELETED_SOON":                        "The KMI entry for the new certificat will be deleted in <willBeDeletedInDays> day(s).",
	"CERTIFICATE_KMI_DATA_WILL_BE_DELETED_TODAY":                       "The KMI entry for the new certificate will be deleted today.",
	"CERTIFICATE_MISSING_CN_FROM_SAN_LIST":                             "The Common Name (CN) is missing from the SAN list for '<keyAlgorithm>' certificate.",
	"CERTIFICATE_MISSING_IN_TRUST_CHAIN":                               "Certificate Missing from the new Trust Chain: <issuerX500Principal>",
	"CERTIFICATE_NOT_ACTIVE_IN_KMI":                                    "The new certificate is not active in KMI.",
	"CERTIFICATE_NOT_PEM_FORMAT":                                       "This certificate format is not supported. The supported format for certificates and trust chains is PEM (base64).",
	"CERTIFICATE_NOT_YET_VALID":                                        "Certificate not yet valid; issuer [<issuer>] serial number [<serialNumber>]: [<exceptionMessage>].",
	"CERTIFICATE_NULL_OR_EMPTY":                                        "Null or empty [<certificateDescription>] Certificate.",
	"CERTIFICATE_PARSING_ERROR":                                        "Error parsing certificate: [<certificateText>]. Cause: [<exceptionMessage>].",
	"CERTIFICATE_SELF_SIGNED":                                          "The Issuer and Subject of the end-entity certificate are identical. This is not allowed.",
	"CERTIFICATE_SERIAL_NUMBER_ON_ANDROID_BLACK_LIST":                  "The '<keyAlgorithm>' certificate may get \"Invalid CA\" errors on some Android devices, due to serial number issues.",
	"CERTIFICATE_SIGNATURE_MISMATCH":                                   "Requested certificate signed with <requestedSignatureAlgorithm> signature algorithm, but got <cpsActualSignatureAlgorithm> (<actualSignatureAlgorithm>).",
	"CERTIFICATE_TRUST_CHAIN_MISSING":                                  "Certificate and/or Trust Chain data is missing.",
	"CERTIFICATE_VS_NETWORK_SAN_REMOVED_FROM_CERT_LIVE_ON_NETWORK":     "SAN name [<sanValue>] removed from certificate is still live on the network.",
	"CROSS_SIGNED_ROOT_IN_TRUST_CHAIN":                                 "Crossed signed roots found in the trust chain.\n<trustChainData>",
	"CSR_EXPIRED":                                                      "The key for '<keyAlgorithm>' certificate has expired. You need to create and submit a new certificate.",
	"CSR_PARSING_ERROR":                                                "Error parsing CSR.",
	"CSR_VS_CERTIFICATE_ADDITIONAL_SAN_IN_SAN_LIST_IN_CERTIFICATE":     "SAN name [<sanValue>] was added to the certificate.",
	"CSR_VS_CERTIFICATE_BOTH_SUBJECT_FIELDS_ARE_NULL_OR_EMPTY":         "Both expected: <expectedValue> and found: <foundValue> values are empty. They cannot be nullOrEmpty at the same time.",
	"CSR_VS_CERTIFICATE_CN_CASE_MISMATCH":                              "The case of the Common Name (CN) on the '<keyAlgorithm>' certificate [<certificateValue>] does not match the CN on the CSR [<csrValue>].",
	"CSR_VS_CERTIFICATE_CN_MISMATCH":                                   "The Common Name (CN) on '<keyAlgorithm>' certificate [<certificateValue>] does not match the CSR [<csrValue>].",
	"CSR_VS_CERTIFICATE_CN_MISSING":                                    "The Common Names (CN) for '<keyAlgorithm>' certificate and CSR must be non-null and non-empty. Certificate CN: [<certificateValue>], CSR CN: [<csrValue>].",
	"CSR_VS_CERTIFICATE_C_FIELD_ADDITIONAL_IN_CERTIFICATE":             "Value for C differs between the CSR and the certificate: missing vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_C_FIELD_MISMATCH":                              "Value for C differs between the CSR and the certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_C_FIELD_MISSING_IN_CERTIFICATE":                "Value for C differs between the CSR and the certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_KEY_MISMATCH":                                  "'<keyAlgorithm>' certificate was not generated from the CSR that Akamai generated.",
	"CSR_VS_CERTIFICATE_L_FIELD_ADDITIONAL_IN_CERTIFICATE":             "Value for L differs between the CSR and the certificate: missing vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_L_FIELD_MISMATCH":                              "Value for L differs between the CSR and the certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_L_FIELD_MISSING_IN_CERTIFICATE":                "Value for L differs between the CSR and the certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_MISSING_SAN_FROM_SAN_LIST_IN_CERTIFICATE":      "SAN name [<sanValue>] is missing from the certificate.",
	"CSR_VS_CERTIFICATE_OU_FIELD_ADDITIONAL_IN_CERTIFICATE":            "Value for OU differs between the CSR and the certificate: missing vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_OU_FIELD_MISMATCH":                             "Value for OU differs between the CSR and the certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_OU_FIELD_MISSING_IN_CERTIFICATE":               "Value for OU differs between the CSR and the certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_O_FIELD_ADDITIONAL_IN_CERTIFICATE":             "Value for O differs between the CSR and the certificate: missing vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_O_FIELD_MISMATCH":                              "Value for O differs between the CSR and the certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_O_FIELD_MISSING_IN_CERTIFICATE":                "Value for O differs between the CSR and the certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_SAN_CASE_MISMATCH":                             "<certificateValue> [<csrValue>] differs in case on the '<keyAlgorithm>' certificate.",
	"CSR_VS_CERTIFICATE_ST_FIELD_ADDITIONAL_IN_CERTIFICATE":            "Value for ST differs between the CSR and the certificate: missing vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_ST_FIELD_MISMATCH":                             "Value for ST differs between the CSR and the certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_ST_FIELD_MISSING_IN_CERTIFICATE":               "Value for ST differs between the CSR and the certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_CASE_MISMATCH":                   "Case mismatch for <subjectfield>. Expected(in CSR): <csrSubjectValue>, found(in '<keyAlgorithm>' certificate): <certificateSubjectValue>",
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH":                        "Value for [<subjectfield>] differs between the CSR and the '<keyAlgorithm>' certificate: [<csrSubjectValue>] vs [<certificateSubjectValue>].",
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH_MISSING_IN_CERTIFICATE": "Value for [<subjectfield>] differs between the CSR and the '<keyAlgorithm>' certificate: [<csrSubjectValue>] vs missing.",
	"CSR_VS_CERTIFICATE_SUBJECT_FIELD_MISMATCH_MISSING_IN_CSR":         "Value for [<subjectfield>] differs between the CSR and the '<keyAlgorithm>' certificate: missing vs [<certificateSubjectValue>].",
	"DNS_NAME_CAA_NOT_VALIDATED":                                       "DNS name <invalidDomainName> CAA auto validation failed.",
	"DNS_NAME_ISSUER_FORBIDDEN_CAA_RECORD":                             "DNS name forbids CA issuer in CAA record.",
	"DNS_NAME_ISSUER_NOT_IN_CAA_RECORD":                                "DNS name <dnsName> allows CA issuers <caaIssuers>. Configured issuers are <issuers>",
	"DNS_NAME_IS_NO_LONGER_CONTAINED":                                  "DNS name <dnsName> is no longer contained by <nameOfSuperSet>; it will be dropped.",
	"DNS_NAME_LONGER_THEN_255_CHARS":                                   "DNS name <invalidDomainName> longer than 255 characters.",
	"DNS_NAME_NOT_CNAMED":                                              "DNS name <invalidDomainName> not CNAMEd for auto validation.",
	"DNS_NAME_NOT_CONTAINED":                                           "DNS name <dnsName> is not contained by <nameOfSuperSet>.",
	"DNS_NAME_NULL_OR_EMPTY":                                           "DNS name is either null or empty.",
	"DNS_NAME_SERVER_ADDRESS_NOT_RESOLVED":                             "DNS Name Server Address Exception when processing <invalidDomainName>",
	"DNS_QUERY_NAME_SERVER_TIMEOUT":                                    "DNS name server timeout when processing <domain>.",
	"DNS_TEXT_PARSE":                                                   "DNS Text Parse Exception when processing <invalidDomainName>",
	"DNS_UNKNOWN_HOST":                                                 "DNS Unknown Host Exception when processing <invalidDomainName>",
	"DOMAIN_NAME_INVALID":                                              "Domain name is invalid.",
	"END_ENTITY_CERT_IN_TRUST_CHAIN":                                   "The end-entity certificate appears in the trust chain. This is not allowed. It is being automatically removed from the trust chain.",
	"EXTRA_CERT_IN_TRUST_CHAIN":                                        "Extra certificates were found in the chain and are being removed.\n<trustChainData>",
	"FIXED_TRUST_CHAIN_PARSING_ERROR":                                  "Error parsing expected trust chains.",
	"INVALID_CERTIFICATE":                                              "There is a problem processing the certificate.  Please contact your Akamai support team to resolve the issue.",
	"INVALID_CSR":                                                      "There is a problem processing the CSR.  Please contact your Akamai support team to resolve the issue.",
	"MULTIPLE_TRUST_CHAINS":                                            "There are multiple trust chains in\n<trustChainData>",
	"NAMED_TRUST_CHAIN_MISMATCH":                                       "Expected to find trust chain:\n    <expectedName>\n    <expectedDescription>\n  Instead found:\n    <actualName>\n    <actualDescription>",
	"NAME_CONSTRAINTS_VIOLATION":                                       "The certificate chain violates at least one name constraint.",
	"OVERLAPPING_TRAFFIC_CLASS":                                        "The following domain(s) overlap domains on another certificate: <sanString>.",
	"RETRY_REQUIRED":                                                   "Action Retry Required",
	"SANS_REMOVED_REQUIRE_ACKNOWLEDGEMENT":                             "The SANs [<sanString>] are scheduled to be removed with this operation. Removing SANs from this enrollment may result in a disruption of your service for TLS connections.",
	"SET_STRICT_CHECK_FALSE":                                           "Set strict CERT check FALSE.",
	"SNI_DNS_OVERLAP":                                                  "Name [<dnsName>] is overlapping DNS name of one or more enrollments.",
	"THIRD_PARTY_BLACKLISTED_TRUST_CHAIN_INTERMEDIATE_CERTIFICATE":     "Third party trust chain intermediate certificate: [<intermediateCertificateText>] is blacklisted.",
	"THIRD_PARTY_BLACKLISTED_TRUST_CHAIN_ROOT_CERTIFICATE":             "Third party trust chain root certificate: [<rootCertificateText>] is blacklisted.",
	"TRUST_CHAIN_DOES_NOT_INCLUDE_TRUSTED_CERTIFICATE":                 "The trust chain for this certificate does not match the expected trust chain for this type of certificate.",
	"TRUST_CHAIN_EMPTY_AND_CERTIFICATE_SIGNED_BY_NON_STANDARD_ROOT":    "The trust chain is empty and the end-entity certificate may have been signed by a non-standard root certificate.",
	"TRUST_CHAIN_EXPIRED_BEFORE_EE":                                    "End entity certificate [<endEntityCn>] with expiration [<endEntityNotAfter>] expires after the trust chain certificate #[<chainEntityCn>] that expires [<chainEntityNotAfter>].",
	"TRUST_CHAIN_EXPIRED_OR_NOT_YET_VALID":                             "Trust chain certificate #[<trustChainOrderNumber>] issuer [<issuer>] serial number [<serialNumber>]: [<exceptionMessage>].",
	"TRUST_CHAIN_HAS_NULL_ISSUER":                                      "Trust chain certificate #[<trustChainOrderNumber>] has a null issuer",
	"TRUST_CHAIN_HAS_NULL_SERIAL_NUMBER":                               "Trust chain certificate #[<trustChainOrderNumber>] has a null serial number",
	"TRUST_CHAIN_INCLUDES_STANDARD_ROOT_CERTIFICATE":                   "The trust chain includes a standard root certificate. This is not a typical practice.",
	"TRUST_CHAIN_INCLUDES_STANDARD_ROOT_CERTIFICATE_DETAILED":          "The trust chain includes a standard root certificate. This is not a typical practice.\n<trustChainData>",
	"TRUST_CHAIN_INVALID":                                              "This certificate trust chain is invalid because no trust chain was found.",
	"TRUST_CHAIN_INVALID_DETAILED":                                     "This certificate trust chain is invalid because no trust chain was found.\n<trustChainData>",
	"TRUST_CHAIN_NOT_PEM_FORMAT":                                       "This trust chain format is not supported. The supported format for certificates and trust chains is PEM (base64).",
	"TRUST_CHAIN_NULL_OR_EMPTY":                                        "Trust chain is empty.",
	"TRUST_CHAIN_NULL_OR_EMPTY_DETAILED":                               "<trustChainDescription> certificate trust chain is invalid or empty.",
	"TRUST_CHAIN_NULL_OR_EMPTY_REPORT":                                 "Trust chain is empty.\n<trustChainData>",
	"TRUST_CHAIN_PARSING_ERROR":                                        "Failed to parse trust chain.",
	"TRUST_CHAIN_PARSING_ERROR_DETAILED":                               "Unable to parse <trustChainDescription> certificate trust chain.",
	"TRUST_CHAIN_PREVIOUS_NULL_OR_EMPTY":                               "Previous Certificate trust chain is null or empty.",
	"TRUST_CHAIN_TERMINATES_WITH_NON_STANDARD_CERTIFICATE":             "The trust chain terminates with a non-standard root certificate.",
	"TRUST_CHAIN_TERMINATES_WITH_NON_STANDARD_CERTIFICATE_DETAILED":    "The trust chain terminates with a non-standard root certificate.\n<trustChainData>",
	"TRUST_CHAIN_VERIFY_FAILED":                                        "The trust chain [<trustChainCn>] and the end entity [<endEntityCn>] failed to verify.",
	"UNEXPECTED_TRUST_CHAIN":                                           "Unexpected trust chain for this certificate.",
	"UNSORTED_TRUST_CHAIN":                                             "Unsorted trust chain downloaded, using\n<trustChainData>",
	"VALIDATION_EXCEPTION":                                             "Validation exception: <exceptionMessage>.",
	"X509_CERTIFICATE_INVALID_SIGNATURE":                               "Really shouldn't happen, x509Certificates with invalid signatures",
}
