name: build
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version-file: 'go.mod'
        - name: Install terraform
          run: make tools.terraform
        - name: Run linter
          run: make lint
        - name: Create build
          run: make build
        - name: Run tests
          run: make test
        - name: Run terraform fmt check
          run: make terraform-fmtcheck
        - name: Run tflint
          run: make terraform-lint